updated all examples to new api
Updated to main api to use bevy 0.10 api

- Comletely removed GAME stage, Use GameState directly instead
- Updated funcion calls that has changed since bevy 0.4

ERROR: title.stylemap can't be loaded

updated assets example to bevy 0.10 api

updated demo, transparency and redraw_demo